# Conda environment for YOLOv8 Aquarium Object Detection - Linux
# Use this with: conda env create -f environment.yml

name: yolov8_aquarium
channels:
  - pytorch
  - nvidia  # For CUDA support
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  
  # Core PyTorch stack (conda for better CUDA integration)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio
  - pytorch-cuda=11.8  # Remove this line if no CUDA GPU
  
  # Data processing (conda-forge for latest versions)
  - numpy>=1.21.0
  - opencv>=4.5.0
  - pillow>=8.0.0
  - matplotlib>=3.3.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  
  # Utilities
  - pyyaml>=6.0
  - tqdm>=4.60.0
  - requests>=2.25.0
  
  # Jupyter (if using notebooks)
  - jupyter>=1.0.0
  - ipywidgets>=7.6.0
  
  # Development tools
  - pip
  
  # Pip-only packages
  - pip:
    - ultralytics>=8.0.0
